---
title: "OSU CPH Biostatistics Supplemental Course Materials"
---

# PUBHBIO 6210

*  [Practice Exercises 0A](./6210-practice-exercises/PracticeExercises_0A.html)
*  [Practice Exercises 1A](./6210-practice-exercises/PracticeExercises_1A.html)
*  [Practice Exercises 1B](./6210-practice-exercises/PracticeExercises_1B.html)
*  [Practice Exercises 1C](./6210-practice-exercises/PracticeExercises_1C.html)
*  [Practice Exercises 1D](./6210-practice-exercises/PracticeExercises_1D.html)
*  [Practice Exercises 2A](./6210-practice-exercises/PracticeExercises_2A.html)
*  [Practice Exercises 2B](./6210-practice-exercises/PracticeExercises_2B.html)
*  [Practice Exercises 2C](./6210-practice-exercises/PracticeExercises_2C.html)
*  [Practice Exercises 2D](./6210-practice-exercises/PracticeExercises_2D.html)
*  [Practice Exercises 3A](./6210-practice-exercises/PracticeExercises_3A.html)
*  [Practice Exercises 3B](./6210-practice-exercises/PracticeExercises_3B.html)
*  [Practice Exercises 3C](./6210-practice-exercises/PracticeExercises_3C.html)
*  [Practice Exercises 4A](./6210-practice-exercises/PracticeExercises_4A.html)
*  [Practice Exercises 4B](./6210-practice-exercises/PracticeExercises_4B.html)
*  [Practice Exercises 4C](./6210-practice-exercises/PracticeExercises_4C.html)
*  [Practice Exercises 4D](./6210-practice-exercises/PracticeExercises_4D.html)
*  [Practice Exercises 5A](./6210-practice-exercises/PracticeExercises_5A.html)
*  [Practice Exercises 5B](./6210-practice-exercises/PracticeExercises_5B.html)
*  [Practice Exercises 5C](./6210-practice-exercises/PracticeExercises_5C.html)
*  [Practice Exercises 5D](./6210-practice-exercises/PracticeExercises_5D.html)
*  [Practice Exercises 6A](./6210-practice-exercises/PracticeExercises_6A.html)
*  [Practice Exercises 6B](./6210-practice-exercises/PracticeExercises_6B.html)
*  [Practice Exercises 6C](./6210-practice-exercises/PracticeExercises_6C.html)
*  [Practice Exercises 7A](./6210-practice-exercises/PracticeExercises_7A.html)
*  [Practice Exercises 7B](./6210-practice-exercises/PracticeExercises_7B.html)
*  [Practice Exercises 7C](./6210-practice-exercises/PracticeExercises_7C.html)

# PUBHBIO 6211

*  [Practice Exercises Block 1](./6211-practice-exercises/PUBHBIO6211_Exercises_Block1.html)
*  [Practice Exercises Block 2](./6211-practice-exercises/PUBHBIO6211_Exercises_Block2.html)
*  [Practice Exercises Block 3](./6211-practice-exercises/PUBHBIO6211_Exercises_Block3.html)
*  [Practice Exercises Block 4](./6211-practice-exercises/PUBHBIO6211_Exercises_Block4.html)
*  [Practice Exercises Block 5](./6211-practice-exercises/PUBHBIO6211_Exercises_Block5.html)
*  [Practice Exercises Block 6](./6211-practice-exercises/PUBHBIO6211_Exercises_Block6.html)
*  [Practice Exercises Block 7](./6211-practice-exercises/PUBHBIO6211_Exercises_Block7.html)
*  [Practice Exercises Block 8](./6211-practice-exercises/PUBHBIO6211_Exercises_Block8.html)
*  [Practice Exercises Block 9](./6211-practice-exercises/PUBHBIO6211_Exercises_Block9.html)
*  [Practice Exercises Block 10](./6211-practice-exercises/PUBHBIO6211_Exercises_Block10.html)
*  [Practice Exercises Block 11](./6211-practice-exercises/PUBHBIO6211_Exercises_Block11.html)

# PUBHBIO 6250

*  [Lecture 1A](./6250-slides/Lecture1A_CourseIntro.html)
*  [Lecture 1B](./6250-slides/Lecture1B_Refresher.html)
*  [Lecture 2A](./6250-slides/Lecture2A_IntroToLogisticReg.html)
*  [Lecture 2B](./6250-slides/Lecture2B_LogisticInterpretation.html)
*  [Lecture 2C](./6250-slides/Lecture2C_LogisticHypoTestsCIs.html)
*  [Lecture 2D](./6250-slides/Lecture2D_MultipleLogisticReg.html)
*  [Lecture 2E](./6250-slides/Lecture2E_MultLogisticTestsCIs.html)
*  [Lecture 3A](./6250-slides/Lecture3A_LogisticEffectModification.html)
*  [Lecture 3B](./6250-slides/Lecture3B_LogisticConfounding.html)
*  [Lecture 3C](./6250-slides/Lecture3C_LogisticCaseControl.html)
*  [Lecture 3D](./6250-slides/Lecture3D_LogisticCollinearityModelFit.html)
*  [Lecture 4A](./6250-slides/Lecture4A_IntroToPoisDist.html)
*  [Lecture 4B](./6250-slides/Lecture4B_IntroToPoisReg.html)
*  [Lecture 4C](./6250-slides/Lecture4C_Pois_InterTestCI.html)
*  [Lecture 4D](./6250-slides/Lecture4D_PoisRegRiskRate.html)
*  [Lecture 5A](./6250-slides/Lecture5A_MultiPoisReg.html)
*  [Lecture 5B](./6250-slides/Lecture5B_PoisRegConfEffMod.html)
*  [Lecture 5C](./6250-slides/Lecture5C_PoisGOF.html)
*  [Lecture 5D](./6250-slides/Lecture5D_PoisRegOverDispZeroInfla.html)
*  [Lecture 6A](./6250-slides/Lecture6A_AppliedExample.html)
*  [Lecture 7A](./6250-slides/Lecture7A_SurvivalReview.html)
*  [Lecture 7B](./6250-slides/Lecture7B_IntroCoxRegression.html)
*  [Lecture 7C](./6250-slides/Lecture7C_CoxRegressionInteractions.html)
*  [Lecture 7D](./6250-slides/Lecture7D_CoxEstimationTesting.html)
*  [Lecture 8A](./6250-slides/Lecture8A_PredictSurvivalProbs.html)
*  [Lecture 8B](./6250-slides/Lecture8B_CheckingPHAssumption.html)
*  [Lecture 8C](./6250-slides/Lecture8C_StratifiedCoxModel.html)
*  [Lecture 8D](./6250-slides/Lecture8D_SelectionBiasSampleSize.html)
*  [Lecture 9A](./6250-slides/Lecture9A_SurveyVocab.html)
*  [Lecture 9B](./6250-slides/Lecture9B_DesignBasedInference.html)
*  [Lecture 9C](./6250-slides/Lecture9C_Weighting.html)
*  [Lecture 9D](./6250-slides/Lecture9D_VarianceFPC.html)
*  [Lecture 10A](./6250-slides/Lecture10A_DomainsAndChiSquare.html)
*  [Lecture 10B](./6250-slides/Lecture10B_SurveyLinearReg.html)
*  [Lecture 10C](./6250-slides/Lecture10C_SurveyLogisticReg.html)
*  [Lecture 10D](./6250-slides/Lecture10D_SurveyDataDisplay.html)
*  [Lecture 11A](./6250-slides/Lecture11A_ChoosingMethods.html)

# Distribution Tables

*  [All tables below on one page](./index_tables.html)
*  [Normal distribution](./distribution-tables/table_normal.html)
*  [Binomial distribution](./distribution-tables/table_binomial.html)
*  [Poisson distribution](./distribution-tables/table_poisson.html)
*  [t distribution](./distribution-tables/table_t.html)
*  [Chi-square distribution](./distribution-tables/table_chisquare.html)
*  [F distribution](./distribution-tables/table_F.html)

