---
title: "PUBHBIO 6210: Practice Exercises 6A"
format:
  html:
    embed-resources: true
    toc: true
    html-math-method: mathjax
    include-in-header: header.html
---

# Exercise 1

For a random sample of 800 males, 35 were observed to have a particular type of cyst. Calculate a 95% confidence interval for the proportion of males in the population who have the cyst.

::: {.answer .hidden}
$\displaystyle n=800, \ph=\frac{35}{800} = 0.04375$

CI: $\displaystyle \ph \pm z^* \sqrt{\frac{\ph(1-\ph)}{n}}$

Critical value from standard normal with 0.05/2=0.025 in upper tail $\rightarrow z^*=1.96$

$\displaystyle 0.04375 \pm 1.96 \sqrt{\frac{0.04375(1-0.04375)}{800}}$

$0.04375 \pm 1.96 \times 0.00723$

$(0.030, 0.058)$
:::

---

# Exercise 2

Suppose that out of 10,000 50- to 54-year-old women sampled whose mother had breast cancer, 400 had breast cancer at some time in their lives. What is the 99% confidence interval for the incidence rate of breast cancer in such a population? 

::: {.answer .hidden}
$\displaystyle n=10000, \ph=\frac{400}{10000} = 0.04$

CI: $\displaystyle \ph \pm z^* \sqrt{\frac{\ph(1-\ph)}{n}}$

Critical value from standard normal with 0.01/2=0.005 in upper tail $\rightarrow z^*=2.58$

$\displaystyle 0.04 \pm 2.58 \sqrt{\frac{0.04(1-0.04)}{10000}}$

$0.04 \pm 2.58 \times 0.001960$

$(0.035, 0.045)$
:::

---

# Exercise 3

In the University of New Hampshire student survey, students reported their GPA. We are interested in the proportion of students who have a GPA lower than 2.5. Summary of the data are in the Stata output below.

(a) What is the estimate of the desired proportion?

::: {.answer .hidden}
$\displaystyle \ph = \frac{47}{243} = 0.1934$
:::

(b) Use this information to test whether the proportion of all students (the population) is equal to 25%.

::: {.answer .hidden}
$H_0: p=0.25$  $p=$ proportion of students at UNH who have a GPA below 2.5 

$H_a: p \ne 0.25$

$\displaystyle z = \frac{\ph-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}} = \frac{0.1934-0.25}{\sqrt{\frac{0.25(1-0.25)}{243}}} = \frac{-0.0566}{0.02778}=-2.04$

Under $H_0, Z \sim N(0,1)$

p-value = $2 \times P(Z > |-2.04|) = 2 \times 0.0207 = 0.0414$

$0.0414 < 0.05$, Reject $H_0$

We have evidence that the proportion of students with GPA below 2.5 is significantly different from 25%.
:::

```{.text .stata}

. gen lowgpa = 0 if gpa > 0

. replace lowgpa = 1 if gpa < 2.5
(47 real changes made)

. tab lowgpa

     lowgpa |      Freq.     Percent        Cum.
------------+-----------------------------------
          0 |        196       80.66       80.66
          1 |         47       19.34      100.00
------------+-----------------------------------
      Total |        243      100.00

```

---

# Exercise 4

In the University of New Hampshire student survey we have information on each student's sex. Use the Stata output below to test whether the proportion of females is significantly different from 50%.

```{.text .stata}

. tab gender

     Gender |
     (male) |      Freq.     Percent        Cum.
------------+-----------------------------------
     Female |        134       55.14       55.14
       Male |        109       44.86      100.00
------------+-----------------------------------
      Total |        243      100.00

```

::: {.answer .hidden}
$\displaystyle \ph = \frac{134}{243} = 0.5514$

$H_0: p=0.5$  $p=$ proportion of students at UNH who are female 

$H_a: p \ne 0.5$

$\displaystyle z = \frac{\ph-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}} = \frac{0.5514-0.5}{\sqrt{\frac{0.5(1-0.5)}{243}}} = \frac{0.0514}{0.0321}=1.60$

Under $H_0, Z \sim N(0,1)$

p-value = $2 \times P(Z > |1.60|) = 2 \times 0.0548 = 0.1096$

$0.1096 > 0.05$, Fail to reject $H_0$

There is no evidence that the proportion of female students in the population is significantly different from 50%.
:::