---
title: "PUBHBIO 6210: Practice Exercises 4C"
format:
  html:
    embed-resources: true
    toc: true
    html-math-method: mathjax
    include-in-header: header.html
---

# Exercise 1

A study samples 15 people, and the mean systolic blood pressure is 127.3 with standard deviation 19.0. 

(a) Calculate a 95% confidence interval for the mean population systolic blood pressure.

::: {.answer .hidden}
ANSWER: (116.8, 137.8)

$\bar{x} \pm t_{n-1}^* \frac{s}{\sqrt{n}}$

$n=15, \bar{x}=127.3, s=19.0$

$t_{n-1}^* = t_{14}^*$ with 0.025 in upper tail $\rightarrow t_{14}^* = 2.145$

$127.3 \pm 2.145 \times \frac{19.0}{\sqrt{15}} = (116.8, 137.8)$
:::

(b) Suppose we want to construct a 99% confidence interval instead.  How will this confidence interval compare to the one in (a) -- wider, narrower, or the same? Calculate this CI to confirm your answer.

::: {.answer .hidden}
ANSWER: wider -- (112.7, 141.9)

Only change is $t_{n-1}^*$ now has 0.005 in upper tail $\rightarrow  t_{14}^* = 2.977$

$127.3 \pm 2.977 \times \frac{19.0}{\sqrt{15}} = (112.7, 141.9)$
:::

(c) Suppose instead the sample size was 30 people (with the same mean and standard deviation) and we want a 95% confidence interval. How will this interval compare to the one in (a) -- wider, narrower, or the same? Calculate this CI to confirm your answer.

::: {.answer .hidden}
ANSWER: narrower -- (120.2, 134.4)

Changes from (a) are that $n=30$ and $t_{n-1}^* = t_{29}^*$ with 0.025 in upper tail $\rightarrow t_{29}^* = 2.045$

$127.3 \pm 2.045 \times \frac{19.0}{\sqrt{30}} = (120.2, 134.4)$
:::

---

# Exercise 2

The Stata output below contains summary statistics for GPA in the New Hampshire student survey data set. Use this information to construct a 95% confidence interval for the mean GPA of students at UNH.

```{.text .stata}

. tabstat gpa, stats(n mean median sd var p25 p75)

    variable |         N      mean       p50        sd  variance       p25       p75
-------------+----------------------------------------------------------------------
         gpa |       218  2.808394     2.805  .4591705  .2108375       2.5       3.1
------------------------------------------------------------------------------------

```

::: {.answer .hidden}
ANSWER: (2.75, 2.87)

$\bar{x} \pm t_{n-1}^* \frac{s}{\sqrt{n}}$

$n=218, \bar{x}=2.808, s=0.459$

$t_{n-1}^* = t_{217}^*$ with 0.025 in upper tail $\rightarrow$ 217 not on table, use infinity (or 120 ok too) $t_{\infty}^* = 1.960$

$2.808 \pm 1.960 \times \frac{0.459}{\sqrt{218}} = (2.75, 2.87)$
:::

---

# Exercise 3

An employee at Yellowstone National Park has measured the time between eruptions of the Old Faithful geyser. He would like to know the average time someone would have to wait to see the geyser erupt. The data he collected are summarized below.

```{.text .stata}

. tabstat waiting, stats(n mean median sd var p25 p75)

    variable |         N      mean       p50        sd  variance       p25       p75
-------------+----------------------------------------------------------------------
     waiting |        21   68.7619        74  15.05624  226.6905        54        84
------------------------------------------------------------------------------------

```

(a) Estimate a 95% confidence interval for the mean waiting time.

::: {.answer .hidden}
ANSWER: (61.9, 75.6)

$\bar{x} \pm t_{n-1}^* \frac{s}{\sqrt{n}}$

$n=21, \bar{x}=68.76, s=15.06$

$t_{n-1}^* = t_{20}^*$ with 0.025 in upper tail $\rightarrow t_{20}^* = 2.086$

$68.76 \pm 2.086 \times \frac{15.06}{\sqrt{21}} = (61.9, 75.6)$
:::

(b) Estimate a 95% one-sided confidence interval with an upper bound.

::: {.answer .hidden}
ANSWER: ($-\infty$, 74.4)

Critical value $t_{n-1}^* = t_{20}^*$ with all 0.05 in upper tail $\rightarrow t_{20}^* = 1.725$

$(-\infty, \bar{x} + t_{n-1}^* \frac{s}{\sqrt{n}}) = (-\infty, 68.76 + 1.725\times \frac{15.06}{\sqrt{21}}) = (-\infty, 74.4)$
:::