---
title: "PUBHBIO 6210: Practice Exercises 1C"
format:
  html:
    embed-resources: true
    toc: true
    html-math-method: mathjax
    include-in-header: header.html
---

# Exercise 1

What is the probability of two die rolls summing to 5, given that (at least) one of the rolls is a 2?

::: {.answer .hidden}
ANSWER: 2/11

Let $A$ = at least one roll is a 2, $B$ = rolls sum to 5

We want $\displaystyle P(B|A) = \frac{P(A \cap B)}{P(A)}$

To find P(A), let $X$ = 2 on first roll, $Y$ = 2 on second roll

$P(A) = P(X \cup Y) = P(X) + P(Y) - P(X \cap Y) = 1/6 + 1/6 - 1/36 = 11/36$

To find $P(A \cap B)$, note that when rolling the die twice you have:

$k=6$ outcomes per roll, repeat experiment (roll die) $n=2$ times $\rightarrow k^n=6^2=36$ total outcomes

Of those, there are only 2 ways you can sum to 5 with one die a 2: \{2,3\}, \{3,2\} 

Therefore, $P(A \cap B) = 2/36$

Thus,

$\displaystyle P(B|A) = \frac{P(A \cap B)}{P(A)} = \frac{2/36}{11/36} = 2/11$

Note: another way to do this would be to write out all the possible ways you can roll 2 die and have at least one of them be a 2 (event $A$) -- that's subsetting the sample space. Then determine what fraction of these have die that sum to 5 (event $B$). So you would have:

Reduced sample space = \{2,1\},\{2,2\},\{2,3\},\{2,4\},\{2,5\},\{2,6\},\{1,2\},\{3,2\},\{4,2\},\{5,2\},\{6,2\} 

 = 11 outcomes

Of these, only 2 of them sum to 5: \{2,3\},\{3,2\}

Thus the desired probability is 2/11
:::

---

# Exercise 2

Twenty-three brain tumor patients went through a radiotherapy. Time to recurrence of brain metastasis after the treatment was recorded. The proportion of subjects metastasis-free for four weeks was 0.783. The proportion of subjects metastasis-free for eight weeks was 0.566. What is the chance that a patient surviving four weeks would be metastasis-free for another four weeks?

\emph{Hint: being met-free for 8 weeks means being met-free for the first four weeks **and** the next four weeks.}

::: {.answer .hidden}
ANSWER: 0.723

Let $A$ = met-free for 1st 4 weeks, $B$ = met-free for 2nd 4 weeks

Given in problem:

$P(\text{met-free for 1st 4 weeks}) = P(A) = 0.783$

$P(\text{met-free for 8 weeks}) = P(\text{met-free for 1st 4 weeks AND met-free for 2nd 4 weeks})$

 $= P(A \cap B) = 0.566$

Want to know: $P($met-free for 2nd 4 weeks GIVEN met-free for 1st 4 weeks$) = P(B|A)$

$\displaystyle P(B|A) = \frac{P(A \cap B)}{P(A)}= \frac{0.566}{0.783} = 0.723$
:::

---

# Exercise 3

Suppose I have a bag containing two white balls and one black ball. Let:

 $A$ = white ball on the first draw from the bag

 $B$ = black ball on the second draw

(a) If I put balls back into the bag whenever I draw one, are $A$ and $B$ independent?

::: {.answer .hidden}
ANSWER: Yes

$P(B) = 1/3$ regardless of whether the first draw is white $(A)$ or not white $(A^C)$, since the ball that is drawn is replaced. This means that $P(B|A) = P(B|A^C) = P(B)$, so $A$ and $B$ are independent.
:::

(b) What about if I keep balls out of the bag when I draw them?

::: {.answer .hidden}
ANSWER: No

The probability of $B$ changes depending on whether $A$ or $A^C$ happens.

$P(B|A) = 1/2$  ($A$ = white ball drawn and removed on 1st draw, so 1 white and 1 black ball left)

$P(B|A^C) = 0/2$  ($A^C$ = black ball drawn and removed on 1st draw, so 2 white balls left)

$P(B|A) \ne P(B|A^C) \rightarrow$ $A$ and $B$ are not independent
:::